---
title: "Copeland"
output:
  html_document: default
  pdf_document: 
    latex_engine: xelatex
---

```{r}
library(consensus)
```


```{r}
(por01)
(votrix(por01))
copeland(por01, seeTrace = TRUE)
```
```{r}
(por02)
(votrix(por02))
copeland(por02, seeTrace = TRUE)
```


```{r}
(por03)
(votrix(por03))
copeland(por03, seeTrace = TRUE)
```

```{r}
(por04)
(votrix(por04))
copeland(por04, seeTrace = TRUE)
```

```{r}
(por05)
(votrix(por05))
copeland(por05, seeTrace = TRUE)
```

```{r}
(por06)
(votrix(por06))
copeland(por06, seeTrace = TRUE)
```

```{r}
(por07)
(votrix(por07))
copeland(por07, seeTrace = TRUE)
```

```{r}
(por08)
(votrix(por08))
copeland(por08, seeTrace = TRUE)
```

```{r}
(por09)
(votrix(por09))
copeland(por09, seeTrace = TRUE)
```

```{r}
(por10)
(votrix(por10))
copeland(por10, seeTrace = TRUE)
```

```{r}
(por11)
(votrix(por11))
copeland(por11, seeTrace = TRUE)
```

```{r}
(por12)
(votrix(por12))
copeland(por12, seeTrace = TRUE)
```

```{r}
(por13)
(votrix(por13))
copeland(por13, seeTrace = TRUE)
```

```{r}
(por14)
(votrix(por14))
copeland(por14, seeTrace = TRUE)
```

```{r}
(por15)
(votrix(por15))
copeland(por15, seeTrace = TRUE)
```
