set.seed(123)
print("4")
r <- random_profile_of_rankings(4, 4)
t4a <- system.time(kemeny(r))
t4b <- system.time(kemeny(r, parallel = TRUE))
print("5")
r <- random_profile_of_rankings(5, 4)
t5a <- system.time(kemeny(r))
t5b <- system.time(kemeny(r, parallel = TRUE))
print("6")
r <- random_profile_of_rankings(6, 4)
t6a <- system.time(kemeny(r))
t6b <- system.time(kemeny(r, parallel = TRUE))
print("7")
r <- random_profile_of_rankings(7, 4)
t7a <- system.time(kemeny(r))
t7b <- system.time(kemeny(r, parallel = TRUE))
print("8")
r <- random_profile_of_rankings(8, 4)
t8a <- system.time(kemeny(r))
t8b <- system.time(kemeny(r, parallel = TRUE))
print("9")
r <- random_profile_of_rankings(9, 4)
t9a <- system.time(kemeny(r))
t9b <- system.time(kemeny(r, parallel = TRUE))
print("10")
r <- random_profile_of_rankings(10, 4)
t10a <- system.time(kemeny(r))
t10b <- system.time(kemeny(r, parallel = TRUE))

save(t4a, t4b, t5a, t5b, t6a, t6b, t7a, t7b, t8a, t8b, t9a, t9b, t10a, t10b, file = "kemeny")
